config:
  general:
    model-name: 'UnetPlusPlus'
    dataset-name: 'UBEO'
  model:
    logging:
      ml-flow: False
      comet: True
      comet-project-name: 'taxinomisis'
      comet-workspace: 'aleksandarm98'
    parameters:
      learning-rate: 0.00001
      weight-decay: 0.01
      dropout: 0.3
      patience: 5
      number-of-epochs: 50
      batch-size: 6
  input-paths:
    train-images: 's3://{bucket_name}/images/{dataset_name}/train/processed-data/images/'
    train-labels: 's3://{bucket_name}/images/{dataset_name}/train/processed-data/labels/'
    validation-images: 's3://{bucket_name}/images/{dataset_name}/val/images/'
    validation-labels: 's3://{bucket_name}/images/{dataset_name}/val/labels/'

  output-paths:
    model-path: 's3://{bucket_name}/models/{dataset_name}/models/{date}/{model_name}-{datetime}.pt'
    loss-plot-path: 's3://{bucket_name}/models/{dataset_name}/plots/{date}/{model_name}-{datetime}.png'
