version: '3.8'
services:
  image-segmentation-model-training:
    platform: linux/amd64
    build:
      context: ""
      dockerfile: Dockerfile
    container_name: image-segmentation-model-training
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION_NAME: ${AWS_REGION_NAME}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
      COMET_SECRET_KEY: ${COMET_SECRET_KEY}
      CONFIG_PATH: ${CONFIG_PATH}
    volumes:
      - ./config:/config

